package com.ww.database;

import com.ww.model.constant.Category;
import com.ww.model.constant.wisie.WisorType;
import com.ww.model.entity.inside.social.InsideProfile;
import com.ww.repository.inside.social.InsideProfileRepository;
import com.ww.service.auto.AutoJobService;
import lombok.AllArgsConstructor;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;


@Service
@AllArgsConstructor
public class InitAutoService {

    private final InsideProfileRepository insideProfileRepository;

    public void initAutos() {
        List<InsideProfile> insideProfiles = new ArrayList<>();
        insideProfiles.add(new InsideProfile("admin1992", "$2a$12$IZ.dAL3M92Q6XEk9K1YpY.878FBFZZb7qw.oFmXkre7aq8435Oa7u", true));
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder(8);
        insideProfiles.add(new InsideProfile("Murro", encoder).initStats());
        insideProfiles.add(new InsideProfile("Rambo", encoder).initStats().setWisorType(WisorType.WISOR_17));
        insideProfiles.add(new InsideProfile("Krejzol", encoder).initStats());
        insideProfiles.add(new InsideProfile("Tom", encoder).initStats());
        insideProfiles.add(new InsideProfile("qtoś", encoder).initStats());
        insideProfiles.add(new InsideProfile("rapid", encoder).initStats());
        insideProfiles.add(new InsideProfile("Stefan", encoder).initStats());
        insideProfiles.add(new InsideProfile("Paździoch", encoder).initStats(.6, .7, .7, .6, .5, new HashSet<>(Arrays.asList(Category.COUNTRY, Category.EQUATION, Category.NUMBER, Category.RIDDLE, Category.TIME))).setWisorType(WisorType.WISOR_14));
        insideProfiles.add(new InsideProfile("mistrzu", encoder).initStats());
        insideProfiles.add(new InsideProfile("łuki", encoder).initStats());
        insideProfiles.add(new InsideProfile("szybkiPL", encoder).initStats());
        insideProfiles.add(new InsideProfile("fred", encoder).initStats());
        insideProfiles.add(new InsideProfile("wredny89", encoder).initStats());
        insideProfiles.add(new InsideProfile("sympatyk futbolu 82", encoder).initStats());
        insideProfiles.add(new InsideProfile("niewiadomy", encoder).initStats());
        insideProfiles.add(new InsideProfile("samuel L", encoder).initStats().setWisorType(WisorType.WISOR_14));
        insideProfiles.add(new InsideProfile("bandzior", encoder).initStats());
        insideProfiles.add(new InsideProfile("karaTEKA", encoder).initStats());
        insideProfiles.add(new InsideProfile("AJGOR", encoder).initStats());
        insideProfiles.add(new InsideProfile("SMERFny", encoder).initStats());
        insideProfiles.add(new InsideProfile("bond007", encoder).initStats(.8, .8, .7, .7, .7, 4).setWisorType(WisorType.WISOR_25));
        insideProfiles.add(new InsideProfile("strike", encoder).initStats());
        insideProfiles.add(new InsideProfile("UWAŻNY", encoder).initStats());
        insideProfiles.add(new InsideProfile("suzuki", encoder).initStats());
        insideProfiles.add(new InsideProfile("Robert", encoder).initStats());
        insideProfiles.add(new InsideProfile("qwerty", encoder).initStats());
        insideProfiles.add(new InsideProfile("gdańszcznin123", encoder).initStats());
        insideProfiles.add(new InsideProfile("niepoważny2002", encoder).initStats());
        insideProfiles.add(new InsideProfile("roxi", encoder).initStats());
        insideProfiles.add(new InsideProfile("dżery", encoder).initStats());
        insideProfiles.add(new InsideProfile("stanley", encoder).initStats());
        insideProfiles.add(new InsideProfile("Piotruś55", encoder).initStats());
        insideProfiles.add(new InsideProfile("walet", encoder).initStats());
        insideProfiles.add(new InsideProfile("florence", encoder).initStats());
        insideProfiles.add(new InsideProfile("giewont88", encoder).initStats());
        insideProfiles.add(new InsideProfile("Natasha", encoder).initStats(.6, .4, .5, .5, .5, 4).setWisorType(WisorType.WISOR_6));
        insideProfiles.add(new InsideProfile("kris", encoder).initStats());
        insideProfiles.add(new InsideProfile("ooolelele09", encoder).initStats());
        insideProfiles.add(new InsideProfile("jejku88", encoder).initStats());
        insideProfiles.add(new InsideProfile("znowu przegrałem", encoder).initStats());
        insideProfiles.add(new InsideProfile("spoczi7", encoder).initStats());
        insideProfiles.add(new InsideProfile("Pioter", encoder).initStats());
        insideProfiles.add(new InsideProfile("Adrian", encoder).initStats());
        insideProfiles.add(new InsideProfile("edzio listonosz", encoder).initStats());
        insideProfiles.add(new InsideProfile("Ferdek", encoder).initStats());
        insideProfiles.add(new InsideProfile("Halyna", encoder).initStats());
        insideProfiles.add(new InsideProfile("Grażka", encoder).initStats());
        insideProfiles.add(new InsideProfile("urwał", encoder).initStats());
        insideProfiles.add(new InsideProfile("kolos20", encoder).initStats());
        insideProfiles.add(new InsideProfile("mati", encoder).initStats());
        insideProfiles.add(new InsideProfile("krzysio10", encoder).initStats());
        insideProfiles.add(new InsideProfile("robercik", encoder).initStats());
        insideProfiles.add(new InsideProfile("foka84", encoder).initStats());
        insideProfiles.add(new InsideProfile("Łysy", encoder).initStats());
        insideProfiles.add(new InsideProfile("John", encoder).initStats());
        insideProfiles.add(new InsideProfile("mork", encoder).initStats());
        insideProfiles.add(new InsideProfile("xander", encoder).initStats());
        insideProfiles.add(new InsideProfile("Olek", encoder).initStats());
        insideProfiles.add(new InsideProfile("Lucja11", encoder).initStats());
        insideProfiles.add(new InsideProfile("szczęśliwa13", encoder).initStats());
        insideProfiles.add(new InsideProfile("dorsz na obiad", encoder).initStats());
        insideProfiles.add(new InsideProfile("odcedzone ziemniaki", encoder).initStats());
        insideProfiles.add(new InsideProfile("leśna ściółka", encoder).initStats());
        insideProfiles.add(new InsideProfile("smartTV", encoder).initStats());
        insideProfiles.add(new InsideProfile("NoThanks", encoder).initStats());
        insideProfiles.add(new InsideProfile("chrupki", encoder).initStats());
        insideProfiles.add(new InsideProfile("dżony", encoder).initStats());
        insideProfiles.add(new InsideProfile("gargamel", encoder).initStats());
        insideProfiles.add(new InsideProfile("Johnny Cage", encoder).initStats());
        insideProfiles.add(new InsideProfile("Rocky Balboa", encoder).initStats());
        insideProfiles.add(new InsideProfile("Adam Małysz", encoder).initStats().setWisorType(WisorType.WISOR_8));
        insideProfiles.add(new InsideProfile("Andrzej Gołota", encoder).initStats().setWisorType(WisorType.WISOR_18));
        insideProfiles.add(new InsideProfile("Włodzimierz", encoder).initStats());
        insideProfiles.add(new InsideProfile("Vladimir", encoder).initStats());
        insideProfiles.add(new InsideProfile("Witalij", encoder).initStats());
        insideProfiles.add(new InsideProfile("Sasha", encoder).initStats());
        insideProfiles.add(new InsideProfile("Dawidek8", encoder).initStats());
        insideProfiles.add(new InsideProfile("Joasia", encoder).initStats());
        insideProfiles.add(new InsideProfile("Nina", encoder).initStats());
        insideProfiles.add(new InsideProfile("różdżka", encoder).initStats());
        insideProfiles.add(new InsideProfile("uzurpator podium", encoder).initStats());
        insideProfiles.add(new InsideProfile("AK47", encoder).initStats());
        insideProfiles.add(new InsideProfile("co to jest", encoder).initStats());
        insideProfiles.add(new InsideProfile("tajnyAgent", encoder).initStats());
        insideProfiles.add(new InsideProfile("lokator", encoder).initStats());
        insideProfiles.add(new InsideProfile("romek", encoder).initStats());
        insideProfiles.add(new InsideProfile("kolorowy", encoder).initStats());
        insideProfiles.add(new InsideProfile("pani Zofia", encoder).initStats());
        insideProfiles.add(new InsideProfile("Szanowny Ziomek", encoder).initStats());
        insideProfiles.add(new InsideProfile("mieszkaniec metropolii", encoder).initStats());
        insideProfiles.add(new InsideProfile("Jankes", encoder).initStats());
        insideProfiles.add(new InsideProfile("Gringo", encoder).initStats());
        insideProfiles.add(new InsideProfile("rudy", encoder).initStats());
        insideProfiles.add(new InsideProfile("Asior", encoder).initStats());
        insideProfiles.add(new InsideProfile("ChłopakNaOpak", encoder).initStats());
        insideProfiles.add(new InsideProfile("Krysia z Gdyni", encoder).initStats());
        insideProfiles.add(new InsideProfile("Albercik", encoder).initStats());
        insideProfiles.add(new InsideProfile("Irys", encoder).initStats());
        insideProfiles.add(new InsideProfile("edek sprzedawca", encoder).initStats());
        insideProfiles.add(new InsideProfile("lelum polerum", encoder).initStats());
        insideProfiles.add(new InsideProfile("Tyson", encoder).initStats());
        insideProfiles.add(new InsideProfile("Klawisz", encoder).initStats());
        insideProfiles.add(new InsideProfile("Trudne Sprawy", encoder).initStats());
        insideProfiles.add(new InsideProfile("Czołowy", encoder).initStats());
        insideProfiles.add(new InsideProfile("Afera", encoder).initStats());
        insideProfiles.add(new InsideProfile("Barak", encoder).initStats());
        insideProfiles.add(new InsideProfile("Urgot", encoder).initStats());
        insideProfiles.add(new InsideProfile("Rekin", encoder).initStats());
        insideProfiles.add(new InsideProfile("Padzi", encoder).initStats());
        insideProfiles.add(new InsideProfile("Gliniak", encoder).initStats());
        insideProfiles.add(new InsideProfile("Hjundek", encoder).initStats(.6, .7, .63, .7, .8, 6).setWisorType(WisorType.WISOR_12));
        insideProfiles.add(new InsideProfile("Termcia", encoder).initStats(.67, .7, .58, .25, .2, 5).setWisorType(WisorType.WISOR_13));
        insideProfiles.add(new InsideProfile("Kitek", encoder).initStats(.36, .8, .65, .9, .9, 5).setWisorType(WisorType.WISOR_30));
        insideProfiles.add(new InsideProfile("Rumcia", encoder).initStats(.55, .65, .6, .3, .6, 6).setWisorType(WisorType.WISOR_47));
        insideProfiles.add(new InsideProfile("Brat Hjundka", encoder).initStats());
        insideProfiles.add(new InsideProfile("Kręcioł", encoder).initStats(.7, .72, .4, .2, .6, 4).setWisorType(WisorType.WISOR_40));
        insideProfiles.add(new InsideProfile("Monster", encoder).initStats());
        insideProfiles.add(new InsideProfile("Rafciu", encoder).initStats());
        insideProfiles.add(new InsideProfile("Szczeniaczek", encoder).initStats(.68, .72, .85, .64, .1, 6).setWisorType(WisorType.WISOR_4));
        insideProfiles.add(new InsideProfile("Weronika", encoder).initStats());
        insideProfiles.add(new InsideProfile("Groot", encoder).initStats());
        insideProfiles.add(new InsideProfile("Prince", encoder).initStats());
        insideProfiles.add(new InsideProfile("Księciunio", encoder).initStats());
        insideProfiles.add(new InsideProfile("Logan", encoder).initStats(.5, .6, .6, .3, .2, 5));
        insideProfiles.add(new InsideProfile("Szaka", encoder).initStats(.6, .52, .6, .5, .5, 4).setWisorType(WisorType.WISOR_9));
        insideProfiles.add(new InsideProfile("Laka", encoder).initStats());
        insideProfiles.add(new InsideProfile("Dunia", encoder).initStats(.35, .68, .59, .8, .8, 4).setWisorType(WisorType.WISOR_1));
        insideProfiles.add(new InsideProfile("Borys", encoder).initStats());
        insideProfiles.add(new InsideProfile("Ripsa", encoder).initStats(.54, .6, .55, .8, .7, 5).setWisorType(WisorType.WISOR_3));
        insideProfiles.add(new InsideProfile("Pipsa", encoder).initStats());
        insideProfiles.add(new InsideProfile("Riki", encoder).initStats());
        insideProfiles.add(new InsideProfile("Tiki", encoder).initStats());
        insideProfiles.add(new InsideProfile("Liki", encoder).initStats());
        insideProfiles.add(new InsideProfile("Piki", encoder).initStats());
        insideProfiles.add(new InsideProfile("Maryla", encoder).initStats(.4, .4, .6, .4, .5, new HashSet<>(Arrays.asList(Category.LYRICS, Category.RIDDLE, Category.TIME))).setWisorType(WisorType.WISOR_10));
        insideProfiles.add(new InsideProfile("Kaszotto", encoder).initStats(.7, .6, .55, .8, .8, 4).setWisorType(WisorType.WISOR_9));
        insideProfiles.add(new InsideProfile("Paralizator", encoder).initStats());
        insideProfileRepository.saveAll(insideProfiles);
        AutoJobService.AUTOS_INITIALIZED = true;
    }

}
