package com.ww.model.constant.wisie;

import java.util.Arrays;
import java.util.List;

public enum MemberWisieStatus {
    NONE,

    WAITING_FOR_QUESTION,
    RECOGNIZING_QUESTION,
    THINKING,

    THINK_KNOW_ANSWER,
    LOOKING_FOR_ANSWER,

    NO_FOUND_ANSWER_LOOKING_FOR,
    FOUND_ANSWER_LOOKING_FOR,

    NOT_SURE_OF_ANSWER,
    RECOGNIZING_ANSWERS,

    NOW_KNOW_ANSWER,
    DOESNT_KNOW_ANSWER,

    ANSWERED,
    SURRENDER,

    WILL_GIVE_RANDOM_ANSWER,
    WONT_GIVE_RANDOM_ANSWER,

    THINKING_WHICH_ANSWER_MATCH,
    THINKING_IF_GIVE_RANDOM_ANSWER,

//LOST CONCENTRATION
    TALKING_ON_THE_PHONE,
    IS_AFRAID_OF_THE_OPPONENT,
    WRITING_AN_SMS,
    DREAMING_ABOUT_VACATION,
    SCRATCHING,
    YAWNING,
    HUMMING_A_SONG,
    WATCHES_THE_AUDIENCE,
    HUNG_UP,
    HAS_MUSCLE_SPASM,
    DRINKING_JUICE,
    WOULD_EAT_SOMETHING,
    NEED_GO_TO_TOILET,

//SKILLS
    //CHANGE_TASK
    WANTS_TO_CHANGE_TASK,
    SUBMITS_APPLICATION,
    //HINT
    HINT_RECEIVED,
    THINKING_IF_USE_HINT,
    WILL_USE_HINT,
    WONT_USE_HINT,
    //COVERALL
    PUTTING_ON_COVERALL,
    COVERALL_READY,
    //PIZZA
    ORDERING_PIZZA,
    PROPOSING_PIZZA,
    THINKING_IF_GET_PIZZA,
    SERVES_PIZZA,
    PREPARING_FOR_EAT_PIZZA,
    WAITING_FOR_OPPONENT_EAT_PIZZA,
    EATING_PIZZA,
    EATEN_PIZZA,
    CLEANING_AFTER_PIZZA,
    //GHOST
        //ghost
    PREPARING_DISGUISE,
    TRYING_TO_SCARE,
    SCARE_SUCCEEDED,
    SCARE_FAILED,
    REMOVING_DISGUISE,
    WAS_CAUGHT,
    WAS_NOT_CAUGHT,
        //victim
    SCARING_ON_IT,
    RUN_AWAY,
    WAS_NOT_SCARED,
    //KIDNAPPING
        //kidnapper
    PREPARING_KIDNAPPING,
    TRYING_TO_KIDNAP,
    KIDNAPPING_SUCCEEDED,
    KIDNAPPING_FAILED,
    CHANGING_CLOTHES,
        //victim
    TRYING_TO_DEFEND,
    WAS_KIDNAPPED,
    WAS_NOT_KIDNAPPED,
    //WATER PISTOL
    WATER_PISTOL_USED_ON_IT,
    CLEANING;

    public static List<MemberWisieStatus> getNoConcentrationActions() {
        return Arrays.asList(DREAMING_ABOUT_VACATION, SCRATCHING, YAWNING, HUNG_UP, NEED_GO_TO_TOILET, HUMMING_A_SONG,
                WATCHES_THE_AUDIENCE, HAS_MUSCLE_SPASM, DRINKING_JUICE, WOULD_EAT_SOMETHING, WRITING_AN_SMS, TALKING_ON_THE_PHONE);
    }

    public static boolean isNoConcentration(MemberWisieStatus action) {
        return getNoConcentrationActions().contains(action);
    }

}
