package com.ww.model.constant.wisie;

import java.util.Arrays;
import java.util.List;

public enum WisieAnswerAction {
    NONE,

    HINT_RECEIVED,
    THINKING_IF_USE_HINT,
    WILL_USE_HINT,
    WONT_USE_HINT,

    WATER_PISTOL_USED_ON_IT,
    CLEANING,

    WAITING_FOR_QUESTION,
    RECOGNIZING_QUESTION,
    THINKING,

    THINK_KNOW_ANSWER,
    LOOKING_FOR_ANSWER,

    NO_FOUND_ANSWER_LOOKING_FOR,
    FOUND_ANSWER_LOOKING_FOR,

    NOT_SURE_OF_ANSWER,
    RECOGNIZING_ANSWERS,

    NOW_KNOW_ANSWER,
    DOESNT_KNOW_ANSWER,

    ANSWERED,
    SURRENDER,

    WILL_GIVE_RANDOM_ANSWER,
    WONT_GIVE_RANDOM_ANSWER,

    THINKING_WHICH_ANSWER_MATCH,
    THINKING_IF_GIVE_RANDOM_ANSWER,

    TALKING_ON_THE_PHONE,
    WRITING_AN_SMS,
    DREAMING_ABOUT_VACATION,
    SCRATCHING,
    YAWNING,
    HUMMING_A_SONG,
    WATCHES_THE_AUDIENCE,
    HUNG_UP,
    HAS_MUSCLE_SPASM,
    DRINKING_JUICE,
    WOULD_EAT_SOMETHING,
    NEED_GO_TO_TOILET;

    public static List<WisieAnswerAction> getNoConcentrationActions() {
        return Arrays.asList(DREAMING_ABOUT_VACATION, SCRATCHING, YAWNING, HUNG_UP, NEED_GO_TO_TOILET, HUMMING_A_SONG,
                WATCHES_THE_AUDIENCE, HAS_MUSCLE_SPASM, DRINKING_JUICE, WOULD_EAT_SOMETHING, WRITING_AN_SMS, TALKING_ON_THE_PHONE);
    }

    public static boolean isNoConcentration(WisieAnswerAction action) {
        return getNoConcentrationActions().contains(action);
    }
}
