package com.ww.model.constant.rival;

public enum RivalStatus {
    OPEN,
    INTRO,
    PREPARING_NEXT_TASK,
    ANSWERING,
    ANSWERING_TIMEOUT,
    ANSWERED,
    CHOOSING_TASK_CATEGORY,
    CHOOSING_TASK_DIFFICULTY,
    CHOOSING_TASK_PROPS,
    RANDOM_TASK_PROPS,
    CHOOSING_WHO_ANSWER,
    CHOSEN_WHO_ANSWER,
    CHOOSING_TASK_TIMEOUT,
    CHOSEN_TASK_CATEGORY,
    CHOSEN_TASK_DIFFICULTY,
    CHOSEN_TASK_PROPS,
    CHANGING_TASK,
    CLOSED,
    DISPOSED,
}
