package com.ww.model.constant.rival;

public enum RivalStatus {
    OPEN,
    INTRO,
    PREPARING_NEXT_TASK,
    ANSWERING,
    ANSWERING_TIMEOUT,
    ANSWERED,
    CHOOSING_TASK_PROPS,
    CHOOSING_WHO_ANSWER,
    CHOSEN_WHO_ANSWER,
    CHOOSING_TASK_PROPS_TIMEOUT,
    CHOSEN_TASK_PROPS,
    CLOSED,
    DISPOSED,
}
