package com.ww.websocket.message;

public enum Message {
    FRIEND_SIGN_IN,
    FRIEND_SIGN_OUT,
    FRIEND_ADD,
    FRIEND_DELETE,
    RIVAL_INVITE,
    RIVAL_CANCEL_INVITE,
    RIVAL_REJECT_INVITE,
    RIVAL_ACCEPT_INVITE,
    BATTLE_CONTENT,
    WAR_CONTENT,
    CAMPAIGN_WAR_CONTENT,
    CHALLENGE_CONTENT,
    REWARD,
}