package com.ww.websocket.message;

public enum Message {
    FRIEND_SIGN_IN,
    FRIEND_SIGN_OUT,
    FRIEND_ADD,
    FRIEND_DELETE,
    BATTLE_INVITE,
    BATTLE_CANCEL_INVITE,
    BATTLE_REJECT_INVITE,
    BATTLE_ACCEPT_INVITE,
    BATTLE_READY_FAST,
    BATTLE_CONTENT,
    WAR_CONTENT,
    WAR_READY_FAST,
    REWARD,
}